val customSchema = StructType(Array(
  StructField("AcceptedAnswerId", DoubleType, nullable = true),
  StructField("AnswerCount", DoubleType, nullable = true),
  StructField("Body", StringType, nullable = true),
  StructField("ClosedDate", TimestampType, nullable = true), 
  StructField("CommentCount", DoubleType, nullable = true),
  StructField("CommunityOwnedDate", TimestampType, nullable = true), 
  StructField("CreationDate", TimestampType, nullable = true), 
  StructField("FavoriteCount", DoubleType, nullable = true),
  StructField("Id", StringType, nullable = true),
  StructField("LastActivityDate", TimestampType, nullable = true), 
  StructField("LastEditDate", TimestampType, nullable = true),
  StructField("LastEditorDisplayName", StringType, nullable = true),
  StructField("LastEditorUserId", StringType, nullable = true),
  StructField("OwnerDisplayName", DoubleType, nullable = true), 
  StructField("OwnerUserId", StringType, nullable = true), 
  StructField("ParentId", StringType, nullable = true), 
  StructField("Score", DoubleType, nullable = true),
  StructField("Tags", StringType, nullable = true),
  StructField("Title", StringType, nullable = true), 
  StructField("_ViewCount", DoubleType, nullable = true))) 


 |-- _AcceptedAnswerId: long (nullable = true)
 |-- _AnswerCount: long (nullable = true)
 |-- _Body: string (nullable = true)
 |-- _ClosedDate: string (nullable = true)
 |-- _CommentCount: long (nullable = true)
 |-- _CommunityOwnedDate: string (nullable = true)
 |-- _CreationDate: string (nullable = true)
 |-- _FavoriteCount: long (nullable = true)
 |-- _Id: long (nullable = true)
 |-- _LastActivityDate: string (nullable = true)
 |-- _LastEditDate: string (nullable = true)
 |-- _LastEditorDisplayName: string (nullable = true)
 |-- _LastEditorUserId: long (nullable = true)
 |-- _OwnerDisplayName: string (nullable = true)
 |-- _OwnerUserId: long (nullable = true)
 |-- _ParentId: long (nullable = true)
 |-- _PostTypeId: long (nullable = true)
 |-- _Score: long (nullable = true)
 |-- _Tags: string (nullable = true)
 |-- _Title: string (nullable = true)
 |-- _ViewCount: long (nullable = true)